### ISSUE TITLE
Solutions à la méthode de suppression des fiches !

### ISSUE THREAD

**Issue by JackCarterSmith** [JackCarterSmith/isen-rm#3]
Il faut qu'on trouve une solution sur le comment gérer la suppression d'une fiche 'proprement' dans le fichier de la DB

**Comment by JackCarterSmith** [comment]
On pourrait puisque l'on connait le nombre de fiches dans la DB faire une copie dans la mémoire de nos fiches à l'aide de :
`malloc(nbr de fiches * sizeof(FICHE));`
Ensuite on peut supprimer notre fiche en question en réécrivant dans notre DB ensuite mais en sautant la fiche à supprimer. (_Réfléchir à un algo..._)

**Comment by Mambalarasse** [comment]
Je crois qu'on a pensé à la même chose, en gros tu veux créer une DB temporaire avec ce que tu veux conserver à l'intérieur, supprimer l'ancienne et renommer la temporaire avec le nom de l'ancienne ? Du coup le paragraphe qui représente ta fiche aura disparut dans ta nouvelle DB.

**Comment by JackCarterSmith** [comment]
En gros c'est ça, juste réfléchir à comment faire un 'truncate' du coup sur la DB en mémoire.

**Comment by Mambalarasse** [comment]
Du coup il faudra aussi faire une fonction de recherche pour déplacer le curseur sur la fiche correspondant à l'ID qu'on va scanf

**Comment by Mambalarasse** [comment]
Si on considère que 1 fiche = 1 ligne, on pourrait faire un système d'incrémentation tout bête avec un for(i<0, i<size, i++) et pour chaque ligne tu fais un strcmp pour voir si l'ID que tu as recherché est le même que celui de ta ligne, si c'est le cas on copie tout sauf elle dans un fichier temporaire, on supprime l'ancien et on renomme le nouveau à partir du nom de l'ancien. Niveau code je pense que c'est possible ! Tu vois le truc ?

**Comment by JackCarterSmith** [comment]
J'ai upload un test de code sur la branche db-core si tu veux voir ce que ça donne. Pas pu vérifier avec une application concrète.

**Comment by JackCarterSmith** [comment]
Fonctionne de façon correct mais des artefacts de mémoire se produise, à voir si cela peut être corriger.
